### ISSUE TITLE
Incorrect validation

### ISSUE THREAD

**Issue by keaukraine** [rwt-to/GeoJSON-Tools#16]
This GeoJSON is valid (rendered on geojson.io) but `geojsonTools.isGeoJSON()` results in error.

```json
{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "properties":{

         },
         "geometry":{
            "type":"MultiLineString",
            "coordinates":[
               [
                  [13, 52],
                  [13.3, 52.2]
               ]
            ]
         }
      }
   ]
}
```

**Comment by nevi-me** [comment]
Hi @keaukraine , although we still use this library, we've shifted a lot to turf. There's `turf-boolean-valid()` if you also use turf, otherwise I'll still fix this issue

**Comment by keaukraine** [comment]
Hello. No, we don't use turf so fixing is important.

**Comment by keaukraine** [comment]
Any update on this?
