### ISSUE TITLE
Complexify method is doing a shift in received array

### ISSUE THREAD

**Issue by jmfly** [rwt-to/GeoJSON-Tools#9]
Hey,

I'm using the complexify method in a plain array of locations and I realized that the method is _eating_ the first position of the input array. 
Looking at the code I found this entry:
   cur = linestring.shift();
That could be changed to cur = linestring[0]? 

Thanks
Julian

**Comment by nevi-me** [comment]
Hey Julian,

I've set a reminder to fix this in the next day. I'll push an update after
looking at the code. Thanks

**Comment by nevi-me** [comment]
Hi @jmfly I've released 0.2.2 with the fix
